name: Node CI

on: [push]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [8.16.2]

    steps:
    - uses: actions/checkout@v1
    - uses: nelonoel/branch-name@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      if: env.BRANCH_NAME=='master'
      run: echo ${{env.BRANCH_NAME}}
